.gitignore, README.md, common.py, iperf.py, logger.py, manifests/pod.yaml.j2, manifests/sriov-pod.yaml.j2, task.py, testSettings.py, trafficFlowTests.py
This commit includes some general refactoring to aid with organizing the various configurations and adds some logic to set reasonable defaults based on the test case ids.
With these changes discrete trials of tests 1 - 24 should work.
Still TODO to achieve basic parity with legacy FT tool:
- Pod to External Testing
- HWOL detection monitor
- Add basic driver to run program from user config rather than hardcoded values
=> Introduce Test 1-24 functionality

.github/workflows/build-and-push.yml, .gitignore, config.yaml, iperf.py, measureCpu.py, measurePower.py, task.py, testSettings.py, trafficFlowTests.py
This commit introduces a new abstract method for tasks. Tasks will have an "output()" function which saves the results of the run in a machine readable format such that it may be consumed by other modules (i.e. scoring component to determine the pass/failure rate of the tests, dashboard to display results).
Additionally output() should handle printing any human-read friendly output to the stdout logs.
=> Add output functionality to FT Tool

arguments.py, config.yaml, eval-config.yaml, evaluator.py, iperf.py, main.py, measureCpu.py, measurePower.py, requirements.txt, task.py, testSettings.py, trafficFlowTests.py
This commit introduces a new module evaluator which takes a path to tft logs and evaluates performance. The threshold for pass/failure can be set via a config file (example provided). The class will generate a machine-readable file containing the results of the flow tests (pass/fail).
The main driver will now be resilant again errors that occur during runtime and return an error code if the flow tests are not completely green.
=> Add Flow Test result evaluator

common.py, evaluator.py, iperf.py, testSettings.py, trafficFlowTests.py
This commit adds reverse testing. As a side effect it also allows multiple connections be run in a single test.
Additional type safety is added by using dataclass for all instances of json / dict data.
=> Add reverse iperf testing

common.py, evaluator.py, iperf.py, main.py, measureCpu.py, measurePower.py, task.py, testSettings.py, trafficFlowTests.py
Aggregate logs to single file
Rather than outputing each individual flow result to a separate file,
compile all tests to a single log. Refactor evaluator to accept a single
file.
Add basic outline to allow plugins to output results. Add a temporary
placeholder for measureCpu and measurePower to store results as json.
TODO: Update plugins to sync with test case intervals.
TODO: Update evaluator to evaluate each plugin
=> Aggregate test results

requirements.txt
Bump PyYAML to 6.0.1 to resolve [issue with cython dependency](https://github.com/yaml/pyyaml/issues/723)
Currently, installing the requirements using a python3.11 venv gives
```
File "<string>", line 201, in get_source_files
File "/tmp/pip-build-env-x1b36mp_/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
raise AttributeError(attr)
AttributeError: cython_sources
```
[PyYAML changelog](https://github.com/yaml/pyyaml/blob/main/CHANGES)
=> Pin PyYAML to 6.0.1, remove cython issue

testConfig.py
Add self.kubeconfig_cx, to find `smartniccluster`
Related config file: <https://gitlab.cee.redhat.com/nst/hw-enablement/nhe/-/blob/master/cluster-deployment-automation-configs/config-cx-nic.yaml?ref_type=heads>
=> Add detection of /root/kubeconfig.smartniccluster

common.py, host.py, iperf.py, k8sClient.py, measureCpu.py, measurePower.py, task.py, thread.py, trafficFlowTests.py, validateOffload.py
`stop` is used almost the same way by all of Task's derived classes. The derived classes similarly all use a `generate_output` function.
1. Make `task.py`'s stop not abstract, provide an implementation to join the threads, set `self._output` to `self.generate_output`
2. Create a `common.BaseOutput` class to abstract common functionality of `IperfOutput` and `PluginOutput`
3. Make a `self.generate_output` abstract function, to return a `common.BaseOutput`
- All derived classes now use Task's `stop` implementation
- ValidateOffload was fixed to correctly count packets. The previous implementation always returned the default value of "None"
This is one of the most potentially breaking changes, and I have several commits to change `stop` and `generate_output`, so I squashed them into this PR …
=> Refactor task.py abstract `stop`

iperf.py, measureCpu.py, measurePower.py
When viewing the logs of the pod, they contain things like "can't open /dev/tty2: No such file or directory"
- Remove the unneeded `-t` in `oc exec`
- I was able to run the tests with this change
=> Remove unused `-t`

iperf.py, task.py, thread.py, trafficFlowTests.py
.join() has no way to actually kill the containers it creates. So let `ReturnValueThread` take a `cleanup_action` to undo the `target` action.
- gives threads the possibility to clean themselves up, in case "join" doesn't return
- pass a timeout to `stop`. After this timeout, join will attempt to kill the thread. If it is not able to, the thread is orphaned
- have IperfServer use the new `cleanup_action` parameter
Depends on #17 to add `Result` in common.py, and the new `stop` implementation
=> Add an undo_target function to return value thread

iperf.py, measureCpu.py, measurePower.py, syncManager.py, task.py, trafficFlowTests.py, validateOffload.py
- Only commit on this branch is [Synchronize threads with SyncManager singleton](https://github.com/wizhaoredhat/ocp-traffic-flow-tests/commit/113d449d855c6c279a4c7ac81de397df23d34d60)
- Rebased on my other changes to Thread & Task to reduce conflicts with them
Resolve #20 
Use barriers to have all of the `ReturnValueThreads` start simultaneously.
Use events for the client to signal when its done, instead of relying on a duration.
=> Synchronize threads

arguments.py, common.py, eval-config.yaml, iperf.py, main.py, netperf.py, task.py, testConfig.py, trafficFlowTests.py, validateOffload.py
- Also removed the requirement to pass in the evaluator config
=> Add Netperf Testing

.github/workflows/lint-test.yml, common.py, evaluator.py, generate_new_eval_config.py, host.py, iperf.py, k8sClient.py, measureCpu.py, mypy.ini, task.py, testConfig.py, testSettings.py, tests/test_common.py, tests/test_evaluator.py, thread.py, trafficFlowTests.py, validateOffload.py
Currently, our github action runs `mypy --install-types --non-interactive --disallow-untyped-defs --ignore-missing-imports .`. 
We will adjust that to run `mypy --strict --config-file mypy.ini .` which is stricter. Fix the code for the typing errors due to that.
Also replace `typing.{List,Dict,Tuple,Union}`.
=> [th/more-typing] use a stricter `mypy` check and fix typing errors for that

perf.py, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py
The formatting that python black produces depends on the version of the tool. The authoritative version is the one from the github action, that is, "24.4.2" which we currently install via pip.
On current Fedora 40, we have 22.12.0.
It's cumbersome if different versions fight over the formatting. Even if the correct solution is to use the same version as used in github, we can avoid this problem by rewriting the code a bit, so that it formats the same with versions 22.12.0 and 24.4.2.
=> [th/black-reformat] style: adjust code so that different black versions format it the same

logger.py
Since we have multiple threads, its useful to see which thread logs what.
Also, align the logging level. Otherwise, lines with different level misalign and are harder to read.
=> [th/log-format] logger: log the thread id and align level

.gitignore
ctags is useful for python. Ignore it's "tags" artifact.
=> [th/gitignore] gitignore: ignore ctags file

pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py
the result handling of the tasks is IMO not good. There are no strong types, and it's quite ill defined what is returned. This should be improved later (by returning typed instances instead of strings or dictionaries or undefined content).
for now, two patches to workaround crashes.
=> [th/plugin-fixes] fix some result handling of the plugin

common.py, evaluator.py, host.py, testConfig.py, tests/test_common.py, tftbase.py
- add `@strict_dataclass` decorator, which can be used to automatically check that a dataclass was initialized with values of the expected type.
- expand `dataclass_from_dict()` to perform the same type checking.
- at the same time, `dataclass_from_dict()` can also handle certain conversions, like string to enum (which is useful, when we load the dict from YAML). This allows us to drop certain `__init__()` methods that worked around this problem.
- mark various dataclasses as frozen. Immutable types a great!!
=> [th/strict-dataclasses] stricter check attributes for dataclasses and make them frozen (immutable)

trafficFlowTests.py
`podman rm --time n` fails unless we also specify "--force". If we do that, we don't need to call a separate "stop" first.
Also, currently Host.run() interprets the cmd string not as shell script, so specifying two commands separated by semicolon is not going to work. That probably should change, because interpreting the cmd as shell script is a useful feature. Anyway, for now, this doesn't work.
=> [th/podman-rm-fix] trafficFlowTest: fix podman-rm command line

tests/test_common.py, tests/test_tftbase.py
"common.py" contains a bunch of general purpose helpers. Theoretically, those could be copied to other projects, and reused (reuse by copy and paste is often not great, but sometimes it's better than the alternatives).
As such, we should also be able to copy-and-paste the test. For that, "test_common.py" should be without extra tftbase dependency. Split the test.
=> [th/split-common-test] tests: split "tests/test_tftbase.py" out of "tests/test_common.py"

.github/workflows/build-pr.yml
Pull requests don't have access to the quay secrets, this thus fails for certain users (or if the pull request originates from another repository, that is not quite clear to me).
Don't push the result, just build it.
---
Note how various the open pull requests have this task failed.
=> [th/github-action-no-push] github: don't push test image for pull requests

iperf.py, main.py, netperf.py, perf.py, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, pluginbase.py, task.py, testConfig.py, testSettings.py, tests/test_testConfig.py, trafficFlowTests.py
- instead of giving only the `TestConfig` to the `Task`, give it the `TestSettings`. This one contains the `TestConfig`, but more additional context about the current part of the test. As `TestSettings` is immutable, this is not a concern.
- add `ConfigDescriptor`, which is an immutable object that refers the (immutable) `TestConfig` and indexes about which part of the test we currently care about. For example, as we iterate over the `test_config.config.tft` list, the `ConfigDescriptor` tells is which the current index to the tft list is (and we can get correct `ConfTest` instance from it).
- with this, the task can know the currently configured namespace. The namespace is configurable in the config YAML, and now accessible at `cfg_descr.get_tft().namespace`. Previously, this setting was …
=> [th/task-context] pass the TestSettings to the Task

perf.py
With "if connection_mode == ConnectionMode.EXTERNAL_IP:" we don't have a template file to render or apply. Fix PerfServer.initialize() for that case.
Fixes: 889791694752 ('task: cleanup initializing tasks')
=> [th/perf-server-fix-initalize-external-ip] perf: fix PerfServer.initialize() with ConnectionMode.EXTERNAL_IP

host.py, tests/test_common.py
a major rework of `Host.run()`. This is how I think it should be done.
- Most importantly, (automatically) log useful messages about the command invocation. Also have various (optional) arguments, to control the logging.
- Handle binary output in a sensible way.
For full details, see the commit message.
If you currently run debug logging, it doesn't really show much. With this patch, we can see all the commands that are invoked (and their output). Quote often, the commands that we invoke are rather interesting for understanding what happens, so this provides IMO a lot of useful debugging output for free.
=> [th/host-log-run] host: log for Host.run() and extend host.Host implementation

host.py
They are currently unused, but they are also not great.
- it should not be a method of Host. Sure, it uses Host.run() to invoke a command, but that doesn't mean that all methods that invoke a command should be methods of the Host. Instead, let Host be about invoking a command, and if you want to add helper functions on top of that, then let them take a Host argument.
- the methods just pass untrusted output to json.loads(). We should have boundaries of trust, and calling to iproute2 should not be trusted to always give valid JSON. We should handle failure or non-JSON output. Granted, the "handling" is failing with some undefined exception. But most callers wouldn't care about this, and they shouldn't be bothered with having to add a try/except around each call.
- likewise, passing …
=> [th/host-no-ipa] host: drop host.Host.{ipa,ipr,all_ports}()

k8sClient.py, task.py
Previously, we get failures like:
```
2024-06-06 10:20:33 DEBUG: cmd[11;localhost]: result `kubectl --kubeconfig /root/kubeconfig.nicmodecluster wait --for=condition=ready pod/sriov-pod-worker-247-server-5201 --timeout=1m `: failed (1); err='Error from server (NotFound): pods "sriov-pod-worker-247-server-5201" not found\n'
2024-06-06 10:20:33 INFO: Result(out='', err='Error from server (NotFound): pods "sriov-pod-worker-247-server-5201" not found\n', returncode=1)
```
At DEBUG level, at least we see the command that was called.  However, at INFO level, we only see the result. It's unclear that the command was. Also, we need two logging lines.
We can do better.
Note that Host.run() already does logging, and it does better than plain
```
logger.info(r)
```
It won't be  perfect. A perfect …
=> [th/k8sclient-error-logging] k8sClient: add "die_on_error" and "may_fail" options to K8sClient.oc()

main.py, trafficFlowTests.py
Often, it is most convenient if we can attach some data to an object.
It can also make code harder to read, because this state is accessible from various places, and it's not clear in which order it gets modified. It can be better (if possible), to pass data around as function parameter. Then at any point, you know that the input-data comes from the caller, and you can look where the caller gets it from.
Drop all state from `TrafficFlowTests` object.
=> [th/traffic-flow-tests-no-state] remove state from TrafficFlowTests object and instead pass data as function arguments/return values

testSettings.py, tftbase.py, trafficFlowTests.py
TestSettings is already immutable, in the sense that no code currently modifies a TestSettings instance after creation.
Make it a frozen dataclass, which helps enforcing the immutablility via typing hints and runtime checks.
Also, make the computed attributes to be property getters.  The benefit is, that it is quite obvious that these getters don't modify the object. More importantly, with the frozen data classes it would be cumbersome to set these values as attributes.
=> [th/test-settings-cleanup] testSettings: make TestSettings a frozen dataclass

common.py, testConfig.py
These helpers are not specific to TestConfig. When we parse YAML (or structured data that comes from YAML or JSON), then may be useful to construct similar immutable data classes. Move the code from "testConfig.py" to "common.py" for reuse.
=> [th/struct-parse-helpers] testConfig: move helpers for parsing yaml to "common.structparse_*"

tests/input1.json, tests/input2.json, tests/input3.json, tests/input4.json
The format will change, and so will need to adjust those files. As they currently are one huge line, the diff becomes not reviewable.
Instead, prettify the files with `jq`.
This is no longer the original style that was written by the test. But as we don't need to test the JSON parser itself, this is equivalent.
=> [th/tests-prettify-json] tests: prettify the JSON test inputs

common.py, tests/test_common.py
"dataclass_from_dict()" cannot read any kinds of data classes (and fields). It should however be able to read the classes we care about.
Extend it, so that Optional[dataclass] and list[dataclass] also works.
Also, add dataclass_to_dict(), which is the opposite operation.
=> [th/dataclass-from-dict-extend] common: add dataclass_to_dict() and extend dataclass_from_dict()

k8sClient.py, pluginValidateOffload.py, task.py
- task: pass "-n namespace" to kubectl commands in Task
- task: add Task.run_oc_exec() helper
- pluginValidateOffload: fix specifying namespace in kubectl command of TaskValidateOffload
- pluginValidateOffload: don't call oc exec command with "sh -c"
=> [th/oc-exec] pass namespace to kubectl/oc and minor cleanups

.flake8
We use python-black for formatting the code. We cannot have trailing white space in the source code.
However, we can have white space inside a (multiline) string. In that case, the space is intentional. Suppress the warning, it doesn't seem useful.
=> [th/flake-w291-trailing-whitespace] flake8: ignore "W291 trailing whitespace" warning

common.py, evaluator.py, perf.py, task.py, testConfig.py, tftbase.py
The dataclasses are immutable, and thus the constructors have a larger number of arguments. For readability, callers should use keyword arguments. Set kw_only=True to force that.
=> [th/dataclasses-kw-only] tftbase: make result/output dataclasses kw_only

common.py
This is useful for a quick way to serialize a class to string, for example to print a logging message.
Logging an object in JSON  can be more useful than str(obj), because the result can be deserialized (first with json.loads() and then common.dataclass_from_dict()).
=> [th/dataclass-to-json] common: add common.dataclass_to_json() helper

evalConfig.py, evaluator.py, tests/test_evaluator.py, trafficFlowTests.py
- don't let the Evaluator object keep state. Instead, the few functions that are there take function arguments and return the result. The caller has to pass them around. Stateless objects are nice, because you don't need to think about their state. In particular, you see where an input argument comes from (from the caller) and you see what we do with the result (return it).
- add `evalConfig.Config` for parsing the `eval-config.yaml`. The benefit is tight validation of the configuration file and a strongly typed object that we can use. Currently the config  only contains the threshold. This will be more useful, if the configuration gets more complex (https://issues.redhat.com/browse/NHE-774)
- use `evalConfig.Config`.
=> [th/eval-config] add EvalConfig and make Evaluator stateless

manifests/host-pod.yaml.j2, manifests/pod.yaml.j2, manifests/sriov-pod.yaml.j2, manifests/tools-pod.yaml.j2, perf.py, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, task.py, tftbase.py
The tests pull `tftbase.TFT_TOOLS_IMG`, which is set to `quay.io/wizhao/tft-tools:latest`. This image gets automatically rebuild on every push to `main` branch.
However, if you are testing a WIP branch that requires an update test image, it is cumbersome.
Allow overriding the test image by setting `TFT_TEST_IMAGE` environment variable. Also, allow overwriting the ImagePullPolicy by setting `TFT_IMAGE_PULL_POLICY` environment variable.
An alternative would be to make those settings part of the TestConfig. However, this option is only useful for testing/developing the flow tests, as such it seems more cumbersome to do it via the TestConfig. Also, you might think if those settings were part of the config YAML, then it would be well known which test image was used by looking at the config. …
=> [th/configure-test-image] allow selecting another test container image for testing

testSettings.py, testType.py
The previous output is rather verbose:
```
2024-06-20 09:13:44 INFO    [th:139821715986240]: Initializing TestType.HTTP server/client for test:
HTTP TEST CONFIGURATION
Test Case TestCaseType.POD_TO_POD_SAME_NODE: SRIOV pod to POD_IP to SRIOV pod - SAME_NODE
Client Node: worker-247
Tenant=True
Index=0
Server Node: worker-247
Exec Persistence: False
Tenant=True
Index=0
2024-06-20 09:13:44 DEBUG   [th:139821715986240]: ...
```
Shorten it to
```
2024-06-20 09:14:58 INFO    [th:140067496519488]: Starting test type=HTTP, test-case=POD_TO_POD_SAME_NODE: SRIOV pod to POD_IP to SRIOV pod - SAME_NODE
Client Node: worker-247
Tenant=True
Index=0
Server Node: worker-247
Exec Persistence: False
Tenant=True
Index=0
2024-06-20 09:14:58 DEBUG   [th:140067496519488]: ...
```
In particular, if you grep for …
=> [th/log-test-start] testType: adjust logging for test start

images/Containerfile, testType.py, testTypeHttp.py, tests/test_testType.py
Inspired by ovn-kuber-traffic-flow-tests (client: [1], server: [2]).
[1] https://github.com/Billy99/ovn-kuber-traffic-flow-tests/blob/17369edc2875b18c1c9df96683518cbc76600fe8/process-cmds.sh#L38
[2] https://github.com/Billy99/ovn-kuber-traffic-flow-tests/blob/17369edc2875b18c1c9df96683518cbc76600fe8/manifests/http-server-pod-v4.yaml.j2#L36
https://issues.redhat.com/browse/NHE-711
=> [th/http-test] http: implement test_type=HTTP for fetching a small file via HTTP

evaluator.py, tests/input5.json, tests/test_evaluator.py, tftbase.py, trafficFlowTests.py
We write the result to a YAML and parse them back.
This mostly uses `common.dataclass_{to,from}_dict()`, except that the list of `TftAggregateOutput` is (at the highest level) not a dataclass (it's a dictionary with a"tft-tests" key and a list of `TftAggregateOutput`). That fact makes the parsing more effort than if it were just a dataclass that we can pass to `common.dataclass_from_dict()`.
Also, use `common.dataclass_to_dict()` in `Evaluator.dump_to_json()`
=> [th/serialize-output] add methods for serializing/parsing the TftAggregateOutput

perf.py, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, testTypeHttp.py, testTypeIperf.py, testTypeNetPerf.py
Note that in some cases we would pass on the command to the PluginOutput. So this changes the output. However, I think the command in the output is only for informational purpose, so this is probably fine. You anyway couldn't copy+paste the command, because the string already previously lacked the "--kubeconfig" and "-n" options, that are automatically added by Task.run_oc().
=> [th/oc-run-exec] task: use Task.run_oc_exec() instead of Task.run_oc()

tftbase.py
Fixes: 825800624bd6 ('all: allow overwriding the image pull police via environment variable')
=> [th/fix-get-tft-image-pull-policy] tft: fix wrong logging in get_tft_image_pull_policy()

common.py, evaluator.py, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, task.py, testType.py, testTypeHttp.py, testTypeIperf.py, testTypeNetPerf.py, tests/input1.json, tests/input2.json, tests/input3.json, tests/input4.json, tests/input5.json, tests/test_pluginValidateOffload.py, tests/test_testTypeNetPerf.py, tests/test_tftbase.py, tftbase.py
- extract parsing of iperf and netperf output to (unit tested) helper functions
- let the parsing don't fail with an exception, instead signal parsing errors in the result (`success=False`).
- let the test already compute the `Bitrate` and embed it in the result. This moves the functionality from the `Evaluator` right to the place where we collect the test result. It also means, the result JSON contains also the bit rate.
- implement bitrate and evaluation for `netperf` test type.
=> [th/eval-result-rework] cleanup evaluation of results

task.py, testTypeHttp.py, testTypeIperf.py, testTypeNetPerf.py
Instead of having TestTypeHandler implementations override _aggregate_output(), move the common code to Task.aggregate_output().
If a TestType implementation really wants to overwrite Task.aggregate_output(), it still can. However, that should not be necessary, because Task.aggregate_output() already all that should be necessary. In particular, it honors IperfOutput's "success" field, which allows Task.aggregate_output()  to do the right thing, without having a per-test-type override.
Task._aggregate_output() still exists and some implementations use it for logging. That part is still task specific, because the base class does not know how to interpret the details of the task.
=> [th/task-aggregate-output] task: let base implementation aggregate_output() handle flow-test result

evaluator.py, pluginValidateOffload.py, pluginbase.py
Of the 3 existing plugins, only "validate_offload" implemented Plugin.eval_log(), which is called by Evaluator for collecting the result. All our plugins should be collected in the results.
Instead of implementing eval_log() for all plugins, rework how it works.
The existing eval_log() implementation of PluginValidateOffload only performed some static check on the PluginOutput. Now, already when running the test, this check is run and PluginOutput.success is set.
Later, the default implementation of Plugin.eval_plugin_output() (previously Plugin.eval_log()) considers PluginOutput.success. This way, we have it implemented for all plugin types, they just need to set the right PluginOutput.success.
Note that Plugin.eval_plugin_output() no longer does anything plugin-specific. It only …
=> [th/eval-all-plugins] evaluator: enable plugin evaluation for all plugins

testSettings.py, tests/input1.json, tests/input2.json, tests/input3.json, tests/input4.json, tests/input5.json, tests/test_tftbase.py, tftbase.py
The input configuration for TFT is a YAML with nested lists of tests, test-cases and connections. Record in the test meta data of the output the indexes, so that we know for which particular test the respective result is.
This allows to associate the test result with the corresponding entry in the test config YAML.
=> [th/test-meta-data-indexes] TestMetadata: record the tft/test_cases/connections indexes

evaluator.py, trafficFlowTests.py
With `evaluator.py` we can evaluate the test result. Note that `main.py` also can do evaluation right after running the test. There is thus duplicated functionality.
Move some of the duplicated code to Evaluator class.
=> [th/refactor-eval-result] evaluator: refactor duplicate code for the evaluation result

pluginbase.py, tftbase.py
Otherwise it is pretty hard to see, which of the results came from which plugin.
=> [th/plugin-result-name] plugin: record the plugin name in PluginResult

pluginMeasurePower.py, tests/test_pluginMeasurePower.py
There is no need for individual logger.error() calls. We already call self.run_oc_exec(), which will log an ERROR with the full output of the command. That is more useful already.
Also, when running ipmitool or parsing its output fails, signal an error and set a reason message.
=> [th/measure-power-parse] pluginMeasurePower: improve error reporting of "measure_power" plugin

README.md, common.py, config.yaml, k8sClient.py, testConfig.py, tests/test_testConfig.py
Make kubeconfig/kubeconfig_infra configurable in the config YAML.
Based on that, we also detect the cluster mode SINGLE/DPU.
Fixes: https://github.com/wizhaoredhat/ocp-traffic-flow-tests/issues/25
The autodetection still works as before. As far as autodetect goes, I think that is good enough. Anything further requires explicit configuration (which this PR adds).
=> [th/config-kubeconfig] make kubeconfig/kubeconfig_infra configurable

images/Containerfile, images/container-entry-point.sh, manifests/tools-pod.yaml.j2, perf.py, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, task.py, testTypeHttp.py, testTypeIperf.py, testTypeNetPerf.py
- `oc delete` is used to cleanup the created pods. Those pods ran `/sbin/init`, which was unkillable by SIGTERM. Hence, every test would waste 30 seconds waiting to kill those containers. Replace that with `tini`, which can be killed fast.
See also: https://github.com/krallin/tini
- enable EPEL/CBR in the test image `quay.io/wizhao/tft-tools:latest`. Also install `psproc-ng` and `coreutils` for better usability of the container when debugging.
=> [th/container-fix-shutdown] fix shutdown of test pods, use tini init process and minor cleanups

common.py
Fixes:
```
common.py:399: error: Non-overlapping identity check (left operand type: "type[Any]", right operand type: "<typing special form>")
```
=> [th/fix-check-type] common: fix type annotation for check_type()

host.py, tests/test_common.py
`errors='surrogateescape'` is a very useful way for handling binary output of commands as if they were strings.
Adjust `Host.run()` to avoid trying to `decode()` such strings twice. We first always decode with `errors='strict'`, to see whether the input is valid UTF-8. If it is, we don't need to decode a second time with `errors='surrogateescape'`. Add that optimization.
=> [th/host-run-surrogateescape] host: avoid duplicate decoding with "errors='surrogateescape'"

print_results.sh
We discussed, and there is the choice that the output format of the tool does not need to be stable. That is, it is not guaranteed that you can parse outputs of a different version of the tool.
Consequently, the output was changed. However, it missed to update print_results.sh for those changes. Fix it.
Fixes: 1b574558c51c ('evaluator: record TestMetadata in TestResult')
CC: @SalDaniele
=> [th/fix-print-results] print_results: fix the script after changing the output format

manifests/host-pod.yaml.j2, manifests/pod.yaml.j2, manifests/sriov-pod.yaml.j2, manifests/tools-pod.yaml.j2, task.py, testTypeHttp.py, testTypeIperf.py, testTypeNetPerf.py
- fix "args" jinja2 variable for "persistent" mode.
- make the "{{ command }}" a plain list via `command: {{ command }}` instead of `command: [ "{{ command }}" ]`. The code that generates the template variables is now in full control of specifying a list, instead of something inside a list inside double quotes.
- in "persistent" mode, let tasks only overwrite "args" (CMD) instead of "command" (ENTRYPOINT). That way, they inherit the entrypoint of the Task parent process, which is sensibly set to `/usr/bin/container-entry-point.sh`.
=> [th/jinja2-command] fix/rework setting the "command" in Jinja2 manifest templates

common.py, tests/test_common.py
The behavior of Jinja2 is not obvious. Add a unit test for exposing the behavior.
Also, move the jinja2 import inside the j2_render_data() function, the
only place where it's used. "common.py" generally works with the
standard lib only, and does not depend on additional pip packages.
Having jinja2 there is a bit ugly. Move it, so you can still fully use
common.py without jinja2, except the functions j2_render() and
j2_render_data().
=> [th/jinja2-render-data] common: add common.j2_render_data() and add test

images/Containerfile
In   `quay.io/wizhao/tft-tools:latest`:
- install python3.11 and setup a venv in `/usr/opt/pyvenv-3.11` with a few pip package.
- copy some of the base python sources to `/usr/opt/ocp-tft`. Currently, this is not very exciting, it will be more interesting when we have a few python utilities there, that we can run via the container (e.g. via `oc exec`).
=> [th/python3-in-test-image] install python3.11 venv and basic python sources in test container image

testTypeHttp.py
Previously, the test would just fetch the page once and quit (fast). It's not clear how the test duration makes sense for the HTTP test, but I think it makes the most sense to poll the page for the requested duration (with a sleep time of 0.2 seconds).
=> [th/http-with-duration] http: honor test "duration" for HTTP test

k8sClient.py
This is mainly useful for manual testing, when firing up K8sClient in the REPL or with `python -c "import k8sClient; ..."`.
All code in the project, still passes an explicit kubeconfig argument. And in those cases, that is probably a good idea.
=> [th/k8sclient-kubeconfig-from-env] k8sClient: use kubeconfig from environment with K8sClient

images/Containerfile, scripts/simple-tcp-server-client.py, testConfig.py, testType.py, testTypeSimple.py, tests/test_testConfig.py, tftbase.py
The purpose is to have an alternative test tool. In this case, it's a relatively simple Python script where the client connects via TCP, sends a message, and the server sends it back.
The point is also, that this script is relatively easily extendable, either for manual testing or to add a new mode. Hence you can specify additional command line arguments in the test configuration.
https://issues.redhat.com/browse/NHE-743
=> [th/simple-tcp-client-server-test] simple: add a test type with a simple python tcp echo server/client

logger.py
For debugging a test, it's important to see how long a command took. Whole seconds granularity is insufficient. Also show the milliseconds part.
=> [th/logger-msec] logger: log milliseconds in test output

images/Containerfile, pluginValidateOffload.py
This replaces parts of https://github.com/wizhaoredhat/ocp-traffic-flow-tests/pull/105
See https://github.com/wizhaoredhat/ocp-traffic-flow-tests/pull/105#issuecomment-2250160362
=> [th/crictl-from-node] don't install crictl/cri-tools in test image and use the one from the node (chroot /host)

common.py, host.py, images/Containerfile, netdev.py, tests/test_netdev.py
This is quite extensive.
- add `netdev.ip_{links,addrs,routes}()` which wraps `ip link|addrs|routes` and parses (and validates) the output. They return Python data classes that are strongly typed.
- same for `ethtool -s`. Add `netdev.ethtool_driver()`.
- add various helpers for read sysfs files.
- since all names in kernel (e.g. interface names in `ip link` or path names in `/sys/class/net`) are not enforced to be in any encoding, the code handles that correctly by using `errors="surrogateescape"`. Almost everything should just work. Of course, the best advise is to stick to always ASCII or at least UTF-8.
- add `netdev.get_device_infos()`, which collects information about all interfaces (pciaddresses, iplink output, ethtool, their VF/VF_REP status) and returns them in a data structure, …
=> [th/netdev-utils] add "netdev.py" with utilities for reading sysfs and getting information from iproute2/ethtool

common.py, jinja2util.py, task.py, tests/test_common.py, tests/test_jinja2util.py
"common" should not depend on additional pip modules. We should be able to copy it somewhere and use with minimal effort (e.g. not need to install additional pip modules).
This is almost the case, except for common.j2_render() and common.j2_render_data(). Move those two functions to a new module "jinja2util.py".
=> [th/jinja2util] common,jinja2util: move common.j2_render() to new "jinja2util.py" module

task.py
- don't use `podman run --init` with our recent test image `quay.io/wizhao/tft-tools:latest`, which already sets the ENTRYPOINT to `/usr/bin/container-entry-point.sh`.
- honor `TFT_IMAGE_PULL_POLICY` for `podman run`.
=> [th/fix-external-perf-server-run] fix podman-run for external-perf-server

netdev.py
Fixes: cf5bfb6e5924 ('netdev: add helper methods for reading sysctl values')
=> [th/fix-get-device-info] netdev: fix get_device_infos() to not iterate duplicate uplink_reps

k8sClient.py
`K8sClient.oc_debug()` calls `kubectl debug` to execute a command on a node.
I initially added this for https://github.com/wizhaoredhat/ocp-traffic-flow-tests/pull/105 , however, it has the downside that it needs to spin up a new pod (so the entire command takes about 2 seconds). If you already have a priviledged pod running that can access the resources you want (e.g. `/host` or the main netns), then a plain `kubectl exec` is going to be faster, and thus preferable. However, that does require you to first start a pod (and maybe clean it up later). So there is more setup involved with that approach, and it's only faster because you only need to start/delete the pod once (instead of every `kubectl debug` call).
Still, as this code was already written, I think it's useful helper to have in …
=> [th/k8sclient-oc-debug] add K8sClient.oc_debug() helper

README.md, config.yaml, eval-config.yaml, manifests/allow-egress-mnp.yaml.j2, manifests/allow-ingress-mnp.yaml.j2, manifests/pod-secondary-network.yaml.j2, task.py, testConfig.py, tests/test_tftbase.py, tftbase.py, trafficFlowTests.py, updated-eval-config.yaml
This MR adds three new tests to test multi-homing and multi-networkpolicies scenarios:
- POD_TO_POD_2ND_INTERFACE_SAME_NODE
- POD_TO_POD_2ND_INTERFACE_DIFF_NODE
- POD_TO_POD_MULTI_NETWORK_POLICY
These tests assume that a secondary network already exists. A sample network attachment definition to test the changes is given below:
```
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
annotations:
meta.helm.sh/release-name: ovn-kubernetes
meta.helm.sh/release-namespace: default
name: ovn-secondary
namespace: default
labels:
tft-tests: "{{ index }}"
spec:
config: '{ "cniVersion": "0.4.0", "name": "ovn-secondary", "netAttachDefName": "default/ovn-secondary",
"isSecondary": true, "subnets": "10.245.0.0/16/24", "mtu": 1400, "type": "ovn-k8s-cni-overlay", …
```
=> Added tests for multi-home and multi-network

host.py, k8sClient.py, task.py, tests/test_common.py, trafficFlowTests.py
Extend `host.Host.run()` with a `check_success` callback. This allows to categorize the `Result` as success/failure, beyond that `returncode==0` check. The benefit is that `host.Host.run()` already makes an effort to provide useful logs with the result, and indicating whether the result is a success/failure will affect the error level and message. It also means, the caller does not need to invest effort to log failures, because the logging that was done automatically is already useful.
=> [th/cleanup-error-logging] cleanup the error handling with host.Host.run()

.github/workflows/lint-test.yml
We already install "jc" via "requirements.txt" file.
=> [th/github-cleanup-install] github: cleanup pip modules in ".github/workflows/lint-test.yml"

host.py
Our logging lines should not span multiple lines, it makes reading the logs harder. Hence, don't print the literal command line but repr(cmd). This nicely quotes and escapes special characters, including newlines.
The downside is, you may no longer be able to copy+paste the log content into the terminal. You would have instead to first paste it into a python REPL, to get the real string. Can't have it all.
Before:
```
$ python -c 'import nhebase.host as h; h.local.run("echo \"hi\nfoo\"")'
2024-08-06 15:17:16.199 DEBUG   [th:140078254828416]: cmd[1;localhost]: call `echo "hi
foo"`
2024-08-06 15:17:16.201 DEBUG   [th:140078254828416]: cmd[1;localhost]: └──> `echo "hi
foo"`: success; out='hi\nfoo\n'
```
After:
```
$ python -c 'import nhebase.host as h; h.local.run("echo \"hi\nfoo\"")' …
```
=> [th/host-run-log] host: log the repr() of the command

.gitignore
temporary files created by VIM while editing a file. Ignore them.
=> [th/gitignore-swp] gitignore: ignore "*.swp" files

Containerfile, ktoolbox/common.py, ktoolbox/test_common.py, mypy.ini, requirements.txt
Previously, we use minicom for opening serial ports. That was nice, because then we can use pexpect for some simple terminal interface navigation.
The problem is that minicom requires a TTY, otherwise it fails with "No cursor motion capability (cm)".
That means, if you run `podman run` without "-t"/"--tty" or `ssh HOST CMD`, you cannot easily use minicom inside the command. Maybe we could wrap minicom inside a tool that creates a tty (tmux?), but that seems cumbersome as well. Instead, use pyserial to operate the serial port.
The downside is that we no longer have a command line tool, and we cannot use pexpect anymore. Hence, implement some simple expect(). This should be sufficient for our use case, and should be easy to extend.
Add the class to ktoolbox.common. Note that the pyserial …
=> [th/serial-expect] common: add common.Serial class for a simple minicom+pexpect

ktoolbox/netdev.py
- netdev: fix handling non-ethernet addresses in netdev.ip_links()
- netdev: add option to reject reserved names in netdev.normalize_ifname()
- netdev: filter out special files from netdev.get_ifnames()
- netdev: tighten up regular expression for netdev.validate_ethaddr()
=> [th/netdev-special-ifnames] fix handling special interface names and non-Ethernet addresses

.github/workflows/lint-test.yml, Containerfile, requirements.txt
Newer PyYAML is fine too (even better). Otherwise, we would need to update the desired, required version over time.
=> [th/requirements-pyyaml] requirements: accept PyYAML>=6.0.1

mypy.ini
Previously, the right way to run mypy was `mypy --strict .`. Set those
options in "mypy.ini" file. You can still override it on the command
line.
=> [th/mypy-files] mymp: set "files=." in mypy.ini

ktoolbox/netdev.py
Version 7.1.1 (flake8-comprehensions: 3.15.0, mccabe: 0.7.0, pycodestyle: 2.12.1, pyflakes: 3.2.0) CPython 3.11.9 on Linux
```
./ktoolbox/netdev.py:583:13: C420 Unnecessary dict comprehension - rewrite using dict.fromkeys().
./ktoolbox/netdev.py:785:18: C420 Unnecessary dict comprehension - rewrite using dict.fromkeys().
```
=> [th/flake8-dict-from-keys] netdev: fix flake8 warnings by using dict.fromkeys()

.github/workflows/lint-test.yml, Containerfile, ktoolbox/host.py, ktoolbox/test_host.py, requirements.txt
Add a `host.RemoteHost` class that implements the `host.Host` API (in particular, the `host.Host.run()` method). In general, the API should behave very similar whether you run `host.LocalHost().run()` or `host.RemoteHost("localhost", ...).run()`. In particular, the arguments `env`, `cwd`, `sudo` should work in a very similar manner whether you run locally or remotely.
`host.RemoteHost` is mostly stateless and immutable. It has some internal state (the paramiko client), but that is per-thread (thread-local storage) and hidden from the user.
Also add a `log_lineoutput:bool` argument to `Host.run()`. When set to True, we won't log stdout/stderr at the end, but rather line by line. That is useful for long-running commands that print their progress (for example `rsh.run("dnf upgrade -y", …
=> [th/remote-host] add host.RemoteHost for running commands via SSH/paramiko

ktoolbox/common.py
This behaves similar to Rust's unwrap() (hence the name).
It's really only useful for assertion use when we require that the value is set.
In that case, the linter might complain if we use the value as Optional[T].
This is thus both a runtime assertion and to make the linter happy, in one.
Note that the generated error message is not very good because there is no context for a better message (though, you get the backtrace, so it's not horrible). That is why it's only for assertion use.
=> [th/unwrap] common: add unwrap() helper

evalConfig.py, ktoolbox/common.py, ktoolbox/test_common.py, mypy.ini, testConfig.py
Our input configuration is YAML, and we parse it into a `TestConfig` class. The configuration contains many simple types (`str`, `int`, `bool`, `Enum`), which should be handled in a similar fashion.
Add helper methods for handling such types and use them. The benefit is that how to handle a `str`, `int`, `bool`, `Enum` is now a common receipt instead of reimplemented at different places.
There are still complex properties that require specific code for parsing and validating them.
Note that the `common.structparse_pop_*()` methods accept a "default" argument. If the argument is missing, the parameter is mandatory. If it's given, it can be an `Optional[T]` to also return `None` for missing keys. In any case, mypy will understand depending on the "default" argument whether the function …
=> [th/structparse-pop] common,testConfig: add helper methods for parsing simple type in testConfig

ktoolbox/firewall.py, ktoolbox/host.py, ktoolbox/test_firewall.py, ktoolbox/test_host.py
Commits:
- host: let host.Result evaluate in a boolean context
- firewall: add docs for nft_data_masquerade_up() and nft_call()
- firewall: return host.Result from firewall.nft_call() and take shell script
Add doc since the usage may not be obvious. Also, add a unit test, which might help to see the usage.
=> [th/firewall-doc] document firewall methods and minor improvements

Containerfile
these two things seem potentially useful to have in our container.
- install `nftables`. It adds 1.4MB, but IMO size of the container is not a major goal, but being useful is.
- set `WORDIR /opt/ocp-tft`. This way, we can directly `python -c "import ...` our Python code. It's more useful than `/` as working directory.
=> [th/containerfile-workdir] Containerfile: set default workdir to "/opt/ocp-tft" and install nftables

ktoolbox/common.py, ktoolbox/test_common.py
- add special case "unique=True, force_unique=True" to reject empty lists.
- rework to use next(iter()) instead of a for loop.
=> [th/iter-get-first] common: support requesting exactly one element in common.iter_get_first()

README.md, config.yaml, manifests/sriov-pod.yaml.j2, task.py, testConfig.py
We need to be able to test out pod2pod traffic on IPUs. Currently the dpu-operator does not deploy a webhook,so we are modifying the SRIOV pod yaml to be able to use secondary network nad and also have resource requests and limits added to the SRIOV pod if the secondary_network_nad is present.  In addition network-attachment-definition no longer by default should contain the namespace. 
In order to use this feature,
1. add `secondary_network_nad` to the yaml. 
2. `resource_name` is optional, you can set it if you would like. Otherwise the program does fetch it for us.
3. run standard pod to pod traffic on an IPU cluster. Populate config file as normal.
4. Pods will properly pass traffic through the secondary network. 
Jira issue: https://issues.redhat.com/browse/IIC-193
=> Update traffic flow test tool to have sriov pod yaml use secondary network

ktoolbox/host.py, ktoolbox/k8sClient.py, ktoolbox/test_common.py, ktoolbox/test_host.py, trafficFlowTests.py
During cleanup, we always call `kubectl --kubeconfig /root/kubeconfig.nicmodecluster -n default delete multi-networkpolicies -l tft-tests`. But for most test cases we won't have such a resource, so the command fails.
Since `k8sClient.oc()` by default has `may_fail=False`, this results in an error in the log:
```
2024-09-16 20:19:03.270 INFO    [th:140347998742336]: Cleaning pods, services and multi-networkpolicies with label tft-tests in namespace default
2024-09-16 20:19:04.467 ERROR   [th:140347998742336]: cmd[8435;localhost]: └──> 'kubectl --kubeconfig /root/kubeconfig.nicmodecluster -n default delete multi-networkpolicies -l tft-tests': failed (exit 1); err='error: the server doesn\'t have a resource type "multi-networkpolicies"\n'
```
It's important that the log file is not spammed …
=> [th/delete-ignore-noexist] prevent error message in logfile when deleting non-existing `multi-networkpolicies`

evaluator.py, ktoolbox/common.py, main.py, print_results.py
- previously, common.log_config_loggers() would each time add a new handler. That meant, if you call configure logger more than once, multiple handlers are added and multiple lines are printed.
This is not uncommon, because we might want initially setup one logging level, then read further configuration, and reconfigure the loggers with the new level.
Instead, the handler that we add now has a particular internal type common._LogHandler. If such a handler is already registered, subsequent calls will not create a new handler but simply reconfigure the existing one.
- rename common.log_config_loggers() to common.log_config_logger(). While the function takes a variadic list of loggers as argument to configure any number of loggers, this seems the better name. This means to merge …
=> [th/fix-log-config] common: improve log_config_logger() for multiple calls

ktoolbox/common.py, ktoolbox/test_logger.py
The benefit of an ExtendedLogger instance is that it provides additional convenience methods (currently only `error_and_exit()`).
All other Logger methods are delegated to the wrapped logger instance. As the method `error_and_exit()` is stateless, there is no difference between using the extended logger or the wrapped logger.
Hence, with
ext_logger = common.ExtendedLogger("foo")
real_logger = logging.getLogger("foo")
calling a method like `debug()` will yield the same result. That is a promise.
The benefit here is that the extended logger has convenience methods on top. While the user does not get access to them via `logging.getLogger()`, they can create (and cache) an `ExtendedLogger` instance for that. The linter will nicely understand when you may call `logger.error_and_exit()`.
=> common: add ExtendedLogger() class

.github/workflows/build-and-push.yml, .github/workflows/build-pr.yml
In anticipation to this repo moving... ;)
=> Use Github Container Repository

.github/workflows/build-and-push.yml, README.md, tftbase.py
Update repo to use the new image hosted via ghcr.io.
Follow up to https://github.com/wizhaoredhat/ocp-traffic-flow-tests/pull/156
=> Update default image tag

pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, pluginbase.py, testType.py, testTypeHttp.py, testTypeIperf.py, testTypeNetPerf.py, testTypeSimple.py
I think this approach is simpler. That is, it's harder to get wrong and it's fewer lines of code.
That's interesting, when we add more test-types or plugins.
=> [th/rework-register-modules] rework how TestTypeHandler and pluginbase.Plugin modules register

pluginValidateOffload.py, pluginbase.py, print_results.py, tftbase.py
an attempt to make the results easier to read
- for `validate_offload` plugin, give a better error reason that shows the passed traffic and threshold.
- in `PluginResult` (which is also persisted to JSON), show the `msg` on failure and the full `plugin_result` details.
- rework how `print_result.sh` shows the output. In particular, print the plugin result. Also, if a plugin indicates failure, the entire run is marked as failed.
Related to https://issues.redhat.com/browse/NHE-1153 , but does not fully fix it.
=> [th/print-results-improvements] rework how print_results.py shows the result

evaluator.py
Previously we only got:
ValueError: ".IPERF_TCP[0].Normal": mandatory key missing
Now we get:
ValueError: Failure parsing 'eval-config.yaml': ".IPERF_TCP[0].Normal": mandatory key missing
=> [th/error-loading-eval-config] evaluator: improve error message when parsing "eval-config.yaml"

print_results.py
Since "config.yaml" can contain multiple tests and "tft.py" can write multiple result files, so also "print_results.py" should handle multiple files.
That way,
./tft.py -o ft-logs/result- config.yaml
./print_results.py ft-logs/result-*.json
works to check all result files, regardless how many tests are defined in config.yaml.
=> [th/print-results-multiple] print_results: support printing multiple results

eval-config.yaml, evalConfig.py, evaluator.py, generate_eval_config.py, tests/generate-eval-config-output0.yaml, tests/generate-eval-config-output1.yaml, tests/generate-eval-config-output2.yaml, tests/generate-eval-config-output3.yaml, tests/input1-RESULTS, tests/input6-RESULTS, tests/test_evaluator.py, tests/test_tftbase.py, tft.py, tftbase.py
We had a similar tool, however that bitrot and no longer worked. It was
dropped in [1].
Bring something similar back, but it's also quite different.
The tool now takes a list of previous runs. It computes a new threshold
and writes an "eval-config.yaml".
It can also take an existing configuration with the "--config" option.
In that case it will keep the entries from the configuration and only
update the thresholds. With "--tigthen-only", it will only lower the
thresholds, not increase them.
This is an initial approach to answer [2]. Probably there are still
places to improve later. This is added now, so we have a place for doing
such improvements.
[1] https://github.com/wizhaoredhat/ocp-traffic-flow-tests/commit/137b00dcfb4025ab23011d21cb0860c73da922d2
[2] …
=> [th/generate-eval-config] add new tool for generating eval-config thresholds

.github/workflows/build-pr.yml, .gitignore, Containerfile, evaluator.py, generate_eval_config.py, task.py, testTypeHttp.py
As the project was renamed, rename also some other names.
=> [th/ocp-rename] rename various "ocp-{tft,traffic-flow-tests}" names

.github/workflows/build-and-push.yml, README.md, tftbase.py
The repository migrated, so the tag/URL of the container needs to be adjusted.
Also, in the github workflow don't detect the "owner" via a separate build step. Other places in the repository also hard code the actual URL, so if we ever move it again, we anyway have to update those places. Having the owner part detected makes it harder to understand which tag will be used.
---
I didn't actually test this, because the image will only be rebuild when the patch gets merged to `main`. Please extra careful review.
=> [th/ocp-tft-image-update] github: update tft-test-image container URL after migration

README.md, config.yaml, testConfig.py
The project was renamed from "ocp-traffic-flow-tests" to "kubernetes-traffic-flow-tests". Adjust names related to OCP.
The default for "secondary_network_nad" was "ocp-secondary", but only for the test cases POD_TO_POD_2ND_INTERFACE_SAME_NODE (27), POD_TO_POD_2ND_INTERFACE_DIFF_NODE (28) and
POD_TO_POD_MULTI_NETWORK_POLICY (29). For other test cases an unspecified "secondary_network_nad" setting means to use the primary instead.
Update the default. This can break users that run tests 27-29 and don't explicitly configure a "secondary_network_nad" setting. Sorry about that. Please update your configuration.
=> [th/ocp-secondary-nad] testConfig: change the default for "secondary_network_nad" from "ocp-secondary" to "tft-secondary"

requirements.txt
There isn't a relevant change there. This is only to sync the used version with the latest available version.
=> [th/ktoolbox-update] ktoolbox: bump to latest version

testConfig.py, tests/test_testConfig.py, tft.py
The kubeconfig files can be part of the configuration YAML. Or they can be detected defaults based on the files we have on the file system. Also, they can be invalid (e.g. not valid YAML).o
Improve the validation of those files, so that we fail early and with a better error message.
Also, validating the files (and resolving the default values) requires to look at the file system. We want to have a first step (the `TestConfig()` constructor) that only parses and validates the configuration file alone. Only a second step would perform further validation (and check the kubeconfig files on disk). Add a `TestConfig.system_check()` for that purpose.
Benefits:
- better error message for invalid kubeconfig (and at a early stage)
- make `TestConfig()` usable to only validate the configuration …
=> [th/kubeconfig-system-check] improve validation of kubeconfig files and add system_check()

README.md, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, task.py, tftbase.py
- fix handling empty `TFT_MANIFESTS_OVERRIDES=`.
- cleanup `get_tft_manifests_overrides()` and log value
- improve handling of "manifests/yamls" output to not rely on current working directory.
- make "manifests/yamls" directory configurable via `$TFT_MANIFESTS_YAMLS`
=> [th/manifests-yamls] improve handling manifests/yamls directory for rendering YAMLs

pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, task.py, testTypeIperf.py, tftbase.py
- better validate the result when we receive it. This way, we ensure that the result dictionary contains what we expect, or we set `success=False` and a `msg` reason.
- move common code to the `Task.aggregate_output()` parent implementation.
=> [th/aggregate-result-cleanup] cleanup Task.aggregate_output()

trafficFlowTests.py
podman-rm got the "--time" argument in version 4.0 ([1]).
Note that ovn-kubernetes runs tests on Ubuntu 22.04, which installs podman 3.4.4+ds1-1ubuntu1.22.04.3. On such a system, we see
```
2025-03-18T14:01:00.2536339Z 2025-03-18 14:01:00.253 INFO    [th:140076536012800]: Cleaning external containers external-perf-server (if present)
2025-03-18T14:01:00.2783216Z 2025-03-18 14:01:00.278 WARNING [th:140076536012800]: cmd[5;localhost]: └──> 'podman rm --force --time 10 external-perf-server': failed (exit 125); err='Error: unknown flag: --time\n'
```
Avoid this option.
Also, the default appears to be already 10 seconds. Also, we expect that our pods run tini init and terminate quickly, without need to resorting to forceful killing.
[1] …
=> [th/podman-rm-no-time] tft: avoid `--time` argument to `podman rm`

pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, task.py, testTypeHttp.py, testTypeIperf.py, testTypeNetPerf.py, testTypeSimple.py
With a recent change in ktoolbox.kjinja2.render_data(), the function now errors out (by default) if an undefined variable is referenced. That is useful, to find bugs about undefined variables in Jinja2 templates.
There are known cases where we render manifest files for client pods, that refer to `{{port}}` jinja2 variable, but `Task.get_template_args()` does not set that variable. That leads to a crash. Fix that.
But also, let the parent implementation in `Task.get_template_args()` set more of those variables. Instead of subclasses overwriting `get_template_args()`, the Task parent class is already aware of most of those parameters (`pod_name`, `port`, `test_image`, `default_network`). Let the parent class always set those variables, so that subclasses don't need to. This means we less …
=> [th/render-undefined-variables] task: rework setting template variables by moving to parent Task.get_template_args()

scripts/build-container.sh, scripts/simple-tcp-server-client.py
One point of the "simple" test is to allow to hack the test and do
whatever we want (for example, modify the python script).
However, the simple script that we run is still inside the container.
So to modify the script, you would have to rebuild the container and
select it via TFT_TEST_IMAGE environment variable. That is still
cumbersome.
Now, add an "--exec" option. If set, the python script will download
that URL, make it executable and execute it. This way, you can more
easily inject another script to run during the test.
You can specify both "--exec" and "--exec-args" option in tft via "tft[0].connections[0].{server,client}.args" parameter. For example:
tft:
- name: ...
...
connections:
- name: ...
type: "simple"
server:
- name: ...
client:
- name: ...
args: "--exec …
=> [th/simple-exec] add "--exec" option to "simple" test to run arbitrary script instead

evaluator.py, generate_eval_config.py, print_results.py, requirements.txt, task.py, tests/test_evaluator.py, tft.py, tftbase.py, trafficFlowTests.py
- rework the handling of `sys.exit()`
- refactor code in `print_results.py` to make it usable from `tft.py`.
- add a `--check` option to `tft.py`. When set, the behavior is as if the `tft.py` call was automatically followed by a `print_results.py` run. Note that with this, we log the pretty-printed results at the end of `tft.py` and exit with code 1, if any tests failed. Otherwise, `tft.py` command usually succeeds, regardless whether any tests failed.
=> [th/tft-check] add "--check" option to `tft.py` to check the test results

README.md, tft.py
Make this more configurable. The kubeconfig for tenant/infra can now be configured via:
- command line "--kubeconfig"/"--kubeconfig-infra"
- environment variables "$TFT_KUBECONFIG"/"$TFT_KUBECONFIG_INFRA"
- config file "kubeconfig"/"kubeconfig_infra"
- autodetect based on files in "/root/kubeconfig*"
Note that if you configure the kubeconfig/kubeconfig-infra at one kind (e.g. environment variable), then the other one must also come from the same source. For example, if you set "--kubeconfig-infra" on the command line, then the kubeconfig must also be specified on the command line. That is partly because the kubeconfig-infra is optional and may be unset. So when you set "--kubeconfig" without "--kubeconfig-infra", that is an indication that the kubeconfig-infra is unset.
The use is to make …
=> [th/kubeconfig-option] tft: add "--kubeconfig{,-infra}" options to overwrite configuration file

Containerfile
`yq` is 10 MB large, which is ugly to add to our container.
But it seems rather useful, to pretty-print JSON/YAML.
=> [th/add-yq] container: install yq in container

README.md, manifests/host-pod.yaml.j2, manifests/pod-secondary-network.yaml.j2, manifests/pod.yaml.j2, manifests/sriov-pod.yaml.j2, task.py, testConfig.py, tests/test_testConfig.py, tftbase.py
Usually we don't need this, and usually we want to run with restricted permissions to be closer to what the user would do.
However, for testing it can be useful (e.g. to exec tcpdump in a running container). Make it configurable via configuration YAML and `TFT_PRIVILEGED_POD` environment variable.
=> [th/privileged-pod] task: support configuring test pods as priviledged

scripts/simple-exec.sh
By passing an argument to "simple-exec.sh" (e.g. via the "--exec-arg" option), the script downloads another "simple-tcp-server-client.py" to run instead.
That is useful, because we might still want to run something like the "simple-tcp-server-client.py" script, but the one inside in the container is more cumbersome to update during a quick test.
=> [th/simple-exec-improvement] simple: improve "simple-exec.sh" script

pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, task.py
Pods can't contain dots, replace them with dashes if the node name has them.
=> Sanitize node name before creating pod name

manifests/host-pod.yaml.j2, manifests/pod-secondary-network.yaml.j2, manifests/pod.yaml.j2, manifests/sriov-pod.yaml.j2, manifests/tools-pod.yaml.j2, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, requirements.txt, task.py, testConfig.py, tests/test_testConfig.py, tests/test_tftbase.py, tftbase.py
- ktoolbox: bump to latest version
- task: simplify selection of pod template and rename pod files
- task: add "Task.render_pod_file()" helper
- task: avoid redundant Task.out_file_yaml state
- tftbase: add str_sanitize() function for sanitizing string
- task: sanitize unusual characters in the pod name
- task: make "node_name_sanitized" a property
- testConfig: validate ConfNodeBase.name to be a valid DNS name
- manifests: quote the {node,pod}_name Jinja variables in YAML
=> [th/node-name-cleanup] cleanups around node name

requirements.txt
Previously, we used git+https:// URL with a fixed commit SHA to the ktoolbox version. This has the benefit that the commit SHA cryptographically encodes the code we are going to pull and build.
In jenkins CI, we reuse a venv and install it via `pip install -r requirements.txt`. Sometimes this venv gets corrupted. It is unclear why this happens. Could this be related to rebuilding the ktoolbox package from a git checkout?
Try to use instead the wheel file. ktoolbox automatically builds a wheel file, pushes it to a "gh-pages" branch ([1]) and exposes it on github pages ([2]). See the README ([3]) how that can be used.
We could directly refer to the github pages file using URL
https://thom311.github.io/ktoolbox/wheels/141.7708daaf4f8c/ktoolbox-0.8.0-py3-none-any.whl
but instead get to the …
=> [th/ktoolbox-wheel-rul] ktoolbox: install ktoolbox package using wheel URL
