ovn-kubernetes/kubernetes-traffic-flow-tests

arguments.py, iperf.py, main.py, measureCpu.py, measurePower.py, task.py, testConfig.py, testSettings.py, trafficFlowTests.py
Add argument handling and main driver. Enable pod-to-external tests.
=> Add pod to external

.github/workflows/build-and-push.yml, common.py, config.yaml, iperf.py, manifests/host-pod.yaml.j2, measureCpu.py, measurePower.py, task.py, testConfig.py, testSettings.py, trafficFlowTests.py
This commit introduces some validation of user input and sets reasonable defaults on option arguments.
It also adds the option for iperf UDP testing.
=> Add input validation and UDP testing

arguments.py, common.py, evaluator.py, host.py, iperf.py, k8sClient.py, main.py, measureCpu.py, measurePower.py, task.py, testConfig.py, testSettings.py, thread.py, trafficFlowTests.py, validateOffload.py
Beginning the process of separating out the linting PR.
This commit is simply the result of running `black .`  and manually removing unused imports.
=> Lint with black, remove unnecessary imports

validateOffload.py
- The interface has changed the `_0` is no longer present
=> Change `ovn-k8s-mp0_0` to `ovn-k8s-mp0`

pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, pluginbase.py
It's useful to see in debug logs, which plugins get enabled (and when, and which Tasks they create).
=> [th/plugin-log-enable] plugin: log about enabling plugin

evaluator.py, iperf.py, k8sClient.py, task.py, testConfig.py, tests/test_pluginbase.py, trafficFlowTests.py
3 unrelated patches, posted here together to have less overhead with the pull request.
- tests: add test for loading all Plugin
- all: use collections.abc.Mapping instead of deprecated typing.Mapping
- all: use host.local instead of creating new host.LocalHost() instances
=> [th/misc] minor patches (use host.local, add unit test, use `collections.abc.Mapping`)

evaluator.py, tftbase.py
This will be used later, when already the test run generates the Bitrate result. It will not only be used and known to the Evaluator.
Also, introduce NA (-1) for not available results. For example, TestType.HTTP won't measure the bit rate and it makes no sense.
Also, make it a frozen class and perform strict validation. For convenience, you can pass `int` as tx/rx value, but the constructor will convert them to floats.
=> [th/bitrate] tftbase: move Bitrate class

README.md
Follow up to https://github.com/wizhaoredhat/ocp-traffic-flow-tests/pull/76#issuecomment-2214668515
=> [th/readme-env] README: document environment variables

task.py
Exceptions from threads are caught by the Thread class and returned during join().
Unexpected exceptions are always bugs. We want to notice them early and tear down the process. No need to wait for the Thread.join(), which also causes the log output to be filled with messages from other threads, and the relevant exception log is easy to miss.
While at it, also crash the main thread (and the entire process) on timeout during Thread.join(). That is a bug too.
=> [th/abort-on-exception] task: abort process on uncaught exception from Task's thread

testConfig.py, tests/test_testConfig.py
We detect the ClusterMode based on the precense of some well known KUBECONFIG files. Log the result of the detection.
=> [th/log-kubeconfig] testConfig: log detected KUBECONFIG and KUBECONFIG_INFRA

pluginValidateOffload.py, task.py
validate_offload plugin needs to detect the VF_REP interface.
On Openshift 4.14, that works by parsing the podSandboxId. This no longer works on 4.15+.
Fix that, by instead reading the information form sysfs.
https://issues.redhat.com/browse/NHE-1154
=> [th/validate-offload-vf-rep] fix detecting VF_REP for validate_offload plugin on 4.15

testConfig.py
TestClient for the most part is an immutable object. As such it is inherently thread-safe.
Once exception is TestClient.client(). This will initialize a K8sClient on first call. To an external user, this lazy initialization almost looks as if the client is immutable, because once initialize, it will not change.
However, the code was not thread-safe. Add a lock for this.
=> [th/testConfig-client-lock] testConfig: ensure TestClient.client() is thread-safe

tests/test_netdev.py
These tests call iproute2, the would fail if we don't have it installed. For the tests, that is not always best. Just skip the test in that case.
=> [th/test-no-iproute2] netdev/tests: skip tests if iproute2 is not installed

ktoolbox/host.py, ktoolbox/test_host.py
- support "sudo" and "cwd" arguments with the obvious meaning.
- pass to Host._run() either a shell script (as string) or a argv array. There are now cases where we call subprocess.run(..., shell=False). If the caller specifies `cmd` as string, then it's always a shell script. If the caller specifies it as an argv list, then it may or may not be executed via a shell, depending on the sudo option (but the effect should be very similar).
- catch exceptions from subprocess.run() and convert them to BinResult() failures. The way to report errors from Host.run() is not exceptions. Previously, exceptions were less likely, but now we can get them easier with a non-existing CWD or a non-existing program name in the argv list.
- be clear about when we have a shell script vs. a argv list. This …
=> [th/host-run-sudo] host: add sudo and cwd arguments to host.Host.run()

ktoolbox/common.py, ktoolbox/test_common.py, scripts/simple-tcp-server-client.py
=> [th/etc-hosts-update] add common.eth_hosts_update_file() helper to write `/etc/hosts`

task.py, testConfig.py
Note that "default-network" defaults to "default/default", it thus commonly includes the namespace. Interestingly, the namespace is not the one configured for the test run, but that seems intentional since CDA creates a NAD "default/default". Anyway. Most likely setting "default-network" works both with or without a namespace. If the namespace is omitted, the NAD should be relative to the test's namespace.
For "secondary_network_nad", this should be handled the same. The user shall be able to configure any namespace. They may also omit the namespace, in which case the NAD is in the test's namespace. For tests 27-29, the default is "ocp-secondary" (which is again in the test's namespace).
Adjusts various places so that "secondary_network_nad" works with those assumptions.
CC: @vrindle
=> [th/ns-for-secondary-nad] task: improve "secondary_network_nad" for being with/without namespace

task.py
For running the command, we already ignored the exit code of the command. That is, because usually the command will be stopped by killing the process, and it's often that the exit code is non-zero.
For the stop/cancel command, now also ignore the exit code of the command. Seems there are cases where `killall iperf3` can fail. Note that it can be that the other side already terminated, which causes the iperf3 process to quit (--one-off) and killall to fail. Ignore that condition too.
=> [th/task-ignore-cancel-cmd-error] task: ignore errors from failed commands in task operation

.github/workflows/lint-test.yml, requirements-devel.txt, requirements.txt
- requirements: drop "pyserial" package dependency
- requirements: add "requirements-devel.txt" for extra pip packages
=> [th/pip-requirements] cleanup pip requirements and add "requirements-devel.txt" file

task.py, testConfig.py, testSettings.py
This is a follow up to https://github.com/ovn-kubernetes/kubernetes-traffic-flow-tests/pull/184#discussion_r1897475029
=> [th/conf-node-cleanup] rename and cleanup uses of node config

requirements.txt
Bring in the latest version. Nothing we need here in particular, but it's nice to keep up to date.
=> [th/ktoolbox-update] ktoolbox: bump ktoolbox version to latest

evaluator.py, generate_eval_config.py, pluginMeasureCpu.py, pluginMeasurePower.py, pluginValidateOffload.py, pluginbase.py, print_results.py, requirements.txt, task.py, testConfig.py, testType.py, testTypeIperf.py, tft.py, tftbase.py, trafficFlowTests.py
it's useful to see a line indicating success/failure. Also, show how long the test was running.
while you can figure that out via other means (e.g. look at timestamps from the logs), this should be visible at one glance.
=> [th/log-duration] log summary line including test duration

scripts/simple-tcp-server-client.py
- simple: improve "simple-tcp-server-client.py" script
- simple: log timestamp for "simple-tcp-server-client.py" script
- simple: only send ascii characters back and forth
=> [th/simple-script-improvements] improve simple-tcp-server-client.py script

requirements.txt
This supports KTOOLBOX_LOGFILE, which is useful to collect log (files) of the run.
=> [th/ktoolbox-update] ktoolbox: bump to latest version

README.md
wormhole seems useful. Explain how to use it in the README.
=> [th/readme-wormhole] README: add usage about magic-wormhole
